routes/web.php
<?php

use App\Http\Controllers\ScriptController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'index')->name('home');

Route::resource('scripts', ScriptController::class)
    ->except('edit', 'update', 'destroy')
    ->names('scripts');

app/Models/Script.php
<?php declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use judahnator\Lua\Debug;

final class Script extends Model
{
    use HasFactory;

    protected $casts = [
        'title' => 'string',
        'script' => 'string',
        'runtime' => 'float',
        'result' => 'string',
        'stdout' => 'string',
        'kudos' => 'int',
    ];

    protected $fillable = [
        'title',
        'script',
        'runtime',
        'result',
        'stdout',
        'kudos',
    ];

    public function getAstTokensAttribute(): string
    {
        return Debug::ast($this->getAttribute('script'));
    }

    public function getLexerTokensAttribute(): string
    {
        return Debug::lexer($this->getAttribute('script'));
    }

    public function scopePopular(Builder $query): Builder
    {
        return $query->orderByDesc('kudos');
    }
}

app/Models/User.php
<?php declare(strict_types=1);

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

final class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/KudosController.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\Script;

final class KudosController
{
    /**
     * Increment kudos value.
     *
     * @param Script $script
     */
    public function store(Script $script)
    {
        $script->updateOrFail(['kudos' => $script->getAttribute('kudos') + 1]);
        return response()->json($script);
    }
}

app/Http/Controllers/PreviewController.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use DateInterval;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use judahnator\Lua\Debug;
use judahnator\Lua\Exceptions\TimeoutException;
use judahnator\Lua\Parser;

final class PreviewController extends Controller
{
    public function lexer(Request $request)
    {
        $this->validate($request, ['script' => 'required|string']);
        return response(Debug::lexer($request->get('script')))->header('Content-Type', 'text/plain');
    }

    public function ast(Request $request)
    {
        $this->validate($request, ['script' => 'required|string']);
        return new JsonResponse(Debug::ast($request->get('script')), json: true);
    }

    public function run(Request $request)
    {
        $this->validate($request, ['script' => 'required|string']);

        $parser = Parser::setup($request->get('script'), timeLimit: new DateInterval(config('app.script_timeout')));

        try {
            $start = microtime(true);
            $result = $parser->run()->getValue();
            $end = microtime(true);
        } catch (TimeoutException $e) {
            return response()->json([
                'message' => $e->getMessage(),
            ])->setStatusCode(408);
        }

        return response()->json([
            'runtime' => round(($end - $start) * 1e3, 2),
            'result' => (string)$result,
            'stdout' => $parser->getEnv()->STDIO->out,
        ]);
    }
}

app/Http/Controllers/ScriptController.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\ScriptRequest;
use App\Models\Script;
use DateInterval;
use Illuminate\Http\Response;
use judahnator\Lua\Parser;

final class ScriptController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return response()->view('scripts.index', [
            'scripts' => Script::query()
                ->scopes('popular')
                ->paginate(15)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return response()->view('scripts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ScriptRequest $request
     */
    public function store(ScriptRequest $request)
    {
        $script = new Script($request->validated());
        $parser = Parser::setup($script->getAttribute('script'), timeLimit: new DateInterval(config('app.script_timeout')));

        $start = microtime(true);
        $result = $parser->run();
        $end = microtime(true);

        $script->setAttribute('runtime', round(($end - $start) * 1e3, 2));
        $script->setAttribute('result', $result->getValue());
        $script->setAttribute('stdout', $parser->getEnv()->STDIO->out);

        $script->saveOrFail();

        return response()->redirectToRoute('scripts.show', $script);
    }

    /**
     * Display the specified resource.
     *
     * @param Script $script
     * @return Response
     */
    public function show(Script $script)
    {
        return response()->view('scripts.show', ['script' => $script]);
    }
}

resources/views/index.blade.php
@extends('layouts.main')

@section('heading', 'Devember - Lua Parser')

@section('content')
    @markdown
    # What can I find on this site?

    On this site you can see an option to create and share scripts you write. The window pane will periodically refresh displaying the generated lexer tokens, compiled AST tree, and interpreted results!

    # In Abstract

    This Devember project aimed at showing developers the process of interpreting, parsing, and executing computer code.
    By no means does this project conform to any set standard. The Lexer, AST Compiler, and Parser are all written by
    me, and I was not developing with interoperability in mind. This makes this mostly useful as an example, but is by
    no means meant to serve as an implementation guide.

    ## The Methodology

    In broad terms, the process goes from script to Lexer to Compiler to Parser.

    ### The Lexer

    The Lexer is a script that defines the dictionary for your langauge. It describes what operator tokens exist, how to
    work with numbers, what strings are valid, and so on. Its job is to describe the possible syntax for the language.

    ### Abstract Syntax Tree

    The AST compiler takes the result of the Lexer and composes the "words" into "ideas." In short its job is to
    identify "Expressions" and "Statements." The former represents a value, the later indicates control flow through
    the application.

    ### The Parser

    The job of the parser is to take the result of the AST actually perform the instructions defined in it.

    @endmarkdown
@endsection

resources/views/layouts/main.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Judahnators Devember 2021 Submission">
    <title>{{ config('app.name') }}</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="{{ asset('js/app.js') }}"></script>
</head>
<body>
<div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    <div class="border-end bg-white" id="sidebar-wrapper">
        <div class="list-group list-group-flush">
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{ route('home') }}">Home</a>
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{ route('scripts.index') }}">Scripts</a>
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{ route('scripts.create') }}">Create</a>
        </div>
    </div>

    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item active"><a class="nav-link" href="{{ route('home') }}">Home</a></li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://gitlab.com/judahnator/devember-2021">Source</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Page content-->
        <div class="container-fluid">
            <h1 class="mt-4">@yield('heading')</h1>
            @yield('content')
        </div>
    </div>
</div>

</body>
</html>

resources/views/scripts/create.blade.php
@extends('layouts.main')

@section('heading', 'Script Writer')

@section('content')
    <form action="{{ route('scripts.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-4">
                <p>Write your own script!</p>
                <label for="title">Script Title:</label>
                <input id="title" type="text" name="title" class="form-control" style="background: white;" required>
            </div>

            <div class="col-4">
                <p><b>Runtime:</b> <i id="runtime">Unknown</i></p>
                <p><b>Result:</b> <i id="result">Unknown</i></p>
                <p><b>StdOut:</b> <i id="stdout">Unknown</i></p>
            </div>

            <div class="col-4 d-grid gap-2 mx-auto">
                <button class="btn btn-secondary btn-block" type="button" onclick="preview()">Preview</button>
                <button class="btn btn-primary btn-block" type="submit">Save</button>
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                <label for="script-input" class="form-label">Your Lua Script:</label>
                <textarea id="script-input" name="script"></textarea>
            </div>

            <div class="col-4">
                <label for="lexer-output" class="form-label">Lexer Output</label>
                <textarea disabled id="lexer-output"></textarea>
            </div>

            <div class="col-4">
                <label for="ast-tree" class="form-label">AST Output</label>
                <textarea disabled id="ast-tree"></textarea>
            </div>
        </div>
    </form>

    <script>
        let input = CodeMirror.fromTextArea(
            document.getElementById('script-input'),
            {
                lineNumbers: true,
                value: 'print(\r\n  "The answer to life, the universe, and everything: ",\r\n  42\r\n);',
                mode: "text/x-lua",
            }
        );

        let tokens = CodeMirror.fromTextArea(
            document.getElementById('lexer-output'),
            {
                lineNumbers: true,
                mode: null,
                readOnly: true,
            }
        );

        let astNodes = CodeMirror.fromTextArea(
            document.getElementById('ast-tree'),
            {
                lineNumbers: true,
                mode: "application/json",
                readOnly: true,
            },
        );

        async function preview () {
            try {
                const inputScript = input.getValue();

                tokens.setValue((await axios.post('{{ route('preview.lexer') }}', {script: inputScript})).data);
                astNodes.setValue(JSON.stringify((await axios.post('{{ route('preview.ast') }}', {script: inputScript})).data, null, 2));

                let result = (await axios.post('{{ route('preview.run') }}', {script: inputScript})).data
                document.getElementById('runtime').textContent = result.runtime + "ms";
                document.getElementById('result').textContent = result.result;
                document.getElementById('stdout').textContent = result.stdout;
            } catch (exception) {
                alert(exception.response.data.message);
            }
        }

        input.on("blur", preview);
    </script>
@endsection

resources/views/scripts/index.blade.php
@php /** @var \Illuminate\Pagination\LengthAwarePaginator|\App\Models\Script[] $scripts */ @endphp

@extends('layouts.main')

@section('heading', 'User Scripts')

@section('content')
    <div class="row">
        <div class="col-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Actions</th>
                    <th scope="col">Title</th>
                    <th scope="col">Runtime</th>
                    <th scope="col">Kudos</th>
                    <th scope="col">Submitted</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($scripts as $script)
                    <tr>
                        <th scope="row">
                            <a class="btn btn-primary" href="{{ route('scripts.show', $script) }}">View</a>
                        </th>
                        <td>{{ $script->getAttribute('title') }}</td>
                        <td>{{ $script->getAttribute('runtime') }}ms</td>
                        <td>{{ $script->getAttribute('kudos') }}</td>
                        <td>{{ $script->getAttribute('created_at')->format('Y-m-d') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $scripts->links() }}
        </div>
    </div>
@endsection

resources/views/scripts/show.blade.php
@php /** @var \App\Models\Script $script */ @endphp

@extends('layouts.main')

@section('heading', $script->getAttribute('title'))

@section('content')
    <div class="row">
        <div class="col-4 d-grid gap-2 mx-auto p-4">
            <button class="btn btn-primary" id="kudos" type="button" onclick="kudos()">Kudos: {{ $script->getAttribute('kudos') }}</button>
        </div>

        <div class="col-6 offset-2">
            <p><b>Runtime:</b> <i id="runtime">{{ $script->getAttribute('runtime') }}ms</i></p>
            <p><b>Result:</b> <i id="result">{{ $script->getAttribute('result') }}</i></p>
            <p><b>StdOut:</b> <i id="stdout">{{ $script->getAttribute('stdout') }}</i></p>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="script-input" class="form-label">Script:</label>
            <textarea disabled id="script-input">{{ $script->getAttribute('script') }}</textarea>
        </div>

        <div class="col-4">
            <label for="lexer-output" class="form-label">Lexer Output</label>
            <textarea disabled id="lexer-output">{{ $script->getLexerTokensAttribute() }}</textarea>
        </div>

        <div class="col-4">
            <label for="ast-tree" class="form-label">AST Output</label>
            <textarea disabled id="ast-tree">{{ $script->getAstTokensAttribute() }}</textarea>
        </div>
    </div>

    <script>
        let input = CodeMirror.fromTextArea(
            document.getElementById('script-input'),
            {
                lineNumbers: true,
                mode: "text/x-lua",
                readOnly: true,
            }
        );

        let tokens = CodeMirror.fromTextArea(
            document.getElementById('lexer-output'),
            {
                lineNumbers: true,
                mode: null,
                readOnly: true,
            }
        );

        let astNodes = CodeMirror.fromTextArea(
            document.getElementById('ast-tree'),
            {
                lineNumbers: true,
                mode: "application/json",
                readOnly: true,
            },
        );

        async function kudos() {
            try {
                let response = await axios.post('{{ route('kudos.store', $script) }}')
                document.getElementById('kudos').textContent = 'Kudos: ' + response.data.kudos;
            } catch (exception) {
                alert(exception.response.data.message);
            }
        }
    </script>
@endsection